package com.example.headsandhandstest.authorization.application

enum class SignInValidationError {
    PASSWORD_MUST_CONTAIN_AT_LEAST_SIX_CHARACTERS,
    PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_CAPITAL_LETTER,
    PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_LOWERCASE_LETTER,
    PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_DIGIT,
    EMAIL_NOT_VALID
}